"""Add many-to-many Post-Tag relationship

Revision ID: 429874959c8f
Revises: 6869275fd01c
Create Date: 2022-06-26 02:21:01.868922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429874959c8f'
down_revision = '6869275fd01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
