"""Add password hashing for User

Revision ID: 4604ed2fd7dd
Revises: 01f3ccbeba67
Create Date: 2022-07-02 23:56:29.906298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4604ed2fd7dd'
down_revision = '01f3ccbeba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
