"""Add profile information in User model
Revision ID: 71ce0ed08d12
Revises: 5b17b8d38bbc
Create Date: 2022-07-15 14:01:04.204351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ce0ed08d12'
down_revision = '5b17b8d38bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'location')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
