"""Add author to posts

Revision ID: 93bb8fd93f92
Revises: 2be4552f598c
Create Date: 2022-07-18 19:34:36.048954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bb8fd93f92'
down_revision = '2be4552f598c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_created'), 'post', ['created'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_created'), table_name='post')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
